### ISSUE TITLE
.on("error") doesn't work?

### ISSUE THREAD

**Issue by andreysm** [matthewmatician/xml-flow#12]
When saxStream encounters an invalid xml, it throws an exception (in strict mode). The error handler isn't called, and the exception isn't catched.

I don't see anywhere in the code, where you handle the "error" event. Probably you should forward saxStream.on("error") to emitter.emit("error").  (I'm not an expert in JS, though.)

Best regards

**Comment by jhankim** [comment]
I can reproduce as well, `on('error', (e)=> {})` doesn't actually catch anything.

**Comment by matthewmatician** [comment]
Fixed via #20
