### ISSUE TITLE
Arrays are returned as Object with numeric keys

### ISSUE THREAD

**Issue by leachiM2k** [matthewmatician/xml-flow#14]
Hey,
I've got an issue with xml-flow. Maybe it's caused by node v8's changed array/object behaviour.

My input XML is:
```xml
<?xml version="1.0" encoding="utf-8"?>
<root>
    <test>
        <line>testline</line>
        <chars>
            <item>1</item>
            <item>2</item>
        </chars>
    </test>
</root>
```

results in:
```json
{
  "$name": "test",
  "line": "testline",
  "chars": {
    "0": "1",
    "1": "2"
  }
}
```

As you see, the resulting "chars" array is an object instead of an array.

What I expect is:
```json
{
  "$name": "test",
  "line": "testline",
  "chars": [
    "1",
    "2"
  ]
}
```

I've already found a solution in helper.js -> shallowClone and could provide it to you.

Cheers
Michael

**Comment by matthewmatician** [comment]
Thanks for the fix!
