### ISSUE TITLE
option to change $attrs 

### ISSUE THREAD

**Issue by shahar-bistec** [matthewmatician/xml-flow#23]
Hi,
is it possible to change $attrs to a self picked name?
if not it will be a nice adding so i hope you will consider it.

**Comment by matthewmatician** [comment]
You could easily convert the property-names on the stream of objects as a post-process if you wish. `attrs` is a common convention used in many libraries, and the `$` is there to help prevent the name-collisions, because `<$attrs>` is an invalid tag-name.
