### ISSUE TITLE
Parse CDATA

### ISSUE THREAD

**Issue by marcoalbarelli** [matthewmatician/xml-flow#3]
Hi 
I found your library almost a perfect match for a project of mine.
The only problem is that I need to retrieve CDATA values 
I already modified your code and I'd be glad to propose a PR

The main diff is that at line 47 of xml-flow I added:

    saxStream.on('cdata', function(text) {
        if(topNode) {
            topNode.$markup.push(text);
        }
    });

This gave me the needed output in the $text property
Maybe this can be made a configurable behaviour

**Comment by matthewmatician** [comment]
Should be fixed now!
