### ISSUE TITLE
simplifyObjects not implemented?

### ISSUE THREAD

**Issue by radicand** [matthewmatician/xml-flow#6]
I have a use case for the final output to have attrs merged with the child tags instead of a one or the other. When I went to look for where `simplifyObjects` was handled to do this, I wasn't able to find it implemented in this codebase or in sax-js. Is this unimplemented or is it handled in another library?

**Comment by radicand** [comment]
Ok - I found the issue. Documentation states `simplifyObjects` but the code uses `simplifyNodes`. You just need to update the documentation.

**Comment by matthewmatician** [comment]
Hey Radicand! Thanks for noticing. I've fixed the docs.
