### ISSUE TITLE
entity values not encoded/escaped

### ISSUE THREAD

**Issue by tapmodo** [matthewmatician/xml-flow#8]
Thanks, this library really helped me filter a massive XML (KML) file!

One problem I had was, with input like this:
```
<description>&lt;br&gt;&lt;br&gt;&lt;table class='data' &gt;&lt;/table&gt;</description>
```

Using the `toXml()` utility method on the same, produces output like this:
```
<description><br><br><table class='data' ></table></description>
```
(obviously bad XML)

For my individual case I was able to transform the value of `<description>` specifically before outputting, but if my data was more complicated that would have become impractical quickly.

I tried working on a fix but the *recursive* nature of the `toXml()` method made any nested tags get encoded too. I may continue trying to construct a fix, but any help you can offer would be great.

**Comment by matthewmatician** [comment]
Thanks, @tapmodo, It should be fixed now in version 1.0.0. I've provided a simple escape function built in, but you can add something more robust as needed. See the readme for more information.
